name: cypress

on:
  push:
  pull_request:
    types: [ opened ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Make build
        run: make build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker-public.artifactory.cloudentity.com
          username: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_CLOUDENTITY_REPO_DEV_PASSWORD }}

      - name: Make run-dev
        run: make run-dev

      - name: Run cypress tests
      - uses: cypress-io/github-action@v2
        with:
          working-directory: tests

      - name: Upload cypress screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots

      - name: Upload cypress videos
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: tests/cypress/videos
