name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"
    branches:
      - "*"
jobs:
  plantuml:
    runs-on: ubuntu-latest
    env:
      UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
      - name: Generating diagrams for
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Install deps
        run: |
          apt-get update -yq && apt-get -yq install plantuml graphviz git fonts-ipafont fonts-ipaexfont
      - name: Generate SVG Diagrams
        run: |
          plantuml -v -tsvg ${{steps.getfile.outputs.files}}
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
