name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"

jobs:
  plantuml:
    runs-on: ubuntu-latest
    env:
      UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff HEAD^ HEAD | grep ${{ env.UML_FILES }} | xargs)"

      - name: Print files to generate
        run: |
          echo "Files to generate: ${{steps.getfile.outputs.files}}"

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg ${{steps.getfile.outputs.files}}

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
