// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// OBExternalFinancialInstitutionIdentification4Code Name of the identification scheme, in a coded form as published in an external list.
//
// swagger:model OBExternalFinancialInstitutionIdentification4Code
type OBExternalFinancialInstitutionIdentification4Code string

// Validate validates this o b external financial institution identification4 code
func (m OBExternalFinancialInstitutionIdentification4Code) Validate(formats strfmt.Registry) error {
	return nil
}
