// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OBActiveOrHistoricCurrencyAndAmount10 Transaction charges to be paid by the charge bearer.
//
// swagger:model OBActiveOrHistoricCurrencyAndAmount_10
type OBActiveOrHistoricCurrencyAndAmount10 struct {

	// amount
	// Required: true
	Amount OBActiveCurrencyAndAmountSimpleType `json:"Amount"`

	// currency
	// Required: true
	Currency ActiveOrHistoricCurrencyCode1 `json:"Currency"`
}

// Validate validates this o b active or historic currency and amount 10
func (m *OBActiveOrHistoricCurrencyAndAmount10) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OBActiveOrHistoricCurrencyAndAmount10) validateAmount(formats strfmt.Registry) error {

	if err := m.Amount.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Amount")
		}
		return err
	}

	return nil
}

func (m *OBActiveOrHistoricCurrencyAndAmount10) validateCurrency(formats strfmt.Registry) error {

	if err := m.Currency.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Currency")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OBActiveOrHistoricCurrencyAndAmount10) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OBActiveOrHistoricCurrencyAndAmount10) UnmarshalBinary(b []byte) error {
	var res OBActiveOrHistoricCurrencyAndAmount10
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
