// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OBAccount6 Unambiguous identification of the account to which credit and debit entries are made.
//
// swagger:model OBAccount6
type OBAccount6 struct {

	// account
	Account []*OBAccount6AccountItems0 `json:"Account"`

	// account Id
	// Required: true
	AccountID AccountID `json:"AccountId"`

	// account sub type
	// Required: true
	AccountSubType OBExternalAccountSubType1Code `json:"AccountSubType"`

	// account type
	// Required: true
	AccountType OBExternalAccountType1Code `json:"AccountType"`

	// currency
	// Required: true
	Currency ActiveOrHistoricCurrencyCode0 `json:"Currency"`

	// description
	Description Description0 `json:"Description,omitempty"`

	// maturity date
	// Format: date-time
	MaturityDate MaturityDate `json:"MaturityDate,omitempty"`

	// nickname
	Nickname Nickname `json:"Nickname,omitempty"`

	// opening date
	// Format: date-time
	OpeningDate OpeningDate `json:"OpeningDate,omitempty"`

	// servicer
	Servicer *OBBranchAndFinancialInstitutionIdentification50 `json:"Servicer,omitempty"`

	// status
	Status OBAccountStatus1Code `json:"Status,omitempty"`

	// status update date time
	// Format: date-time
	StatusUpdateDateTime StatusUpdateDateTime `json:"StatusUpdateDateTime,omitempty"`

	// switch status
	SwitchStatus OBExternalSwitchStatusCode `json:"SwitchStatus,omitempty"`
}

// Validate validates this o b account6
func (m *OBAccount6) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccountID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccountSubType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccountType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaturityDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNickname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOpeningDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServicer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatusUpdateDateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSwitchStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OBAccount6) validateAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.Account) { // not required
		return nil
	}

	for i := 0; i < len(m.Account); i++ {
		if swag.IsZero(m.Account[i]) { // not required
			continue
		}

		if m.Account[i] != nil {
			if err := m.Account[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Account" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *OBAccount6) validateAccountID(formats strfmt.Registry) error {

	if err := m.AccountID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("AccountId")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateAccountSubType(formats strfmt.Registry) error {

	if err := m.AccountSubType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("AccountSubType")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateAccountType(formats strfmt.Registry) error {

	if err := m.AccountType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("AccountType")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateCurrency(formats strfmt.Registry) error {

	if err := m.Currency.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Currency")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateDescription(formats strfmt.Registry) error {

	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := m.Description.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Description")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateMaturityDate(formats strfmt.Registry) error {

	if swag.IsZero(m.MaturityDate) { // not required
		return nil
	}

	if err := m.MaturityDate.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("MaturityDate")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateNickname(formats strfmt.Registry) error {

	if swag.IsZero(m.Nickname) { // not required
		return nil
	}

	if err := m.Nickname.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Nickname")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateOpeningDate(formats strfmt.Registry) error {

	if swag.IsZero(m.OpeningDate) { // not required
		return nil
	}

	if err := m.OpeningDate.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("OpeningDate")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateServicer(formats strfmt.Registry) error {

	if swag.IsZero(m.Servicer) { // not required
		return nil
	}

	if m.Servicer != nil {
		if err := m.Servicer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Servicer")
			}
			return err
		}
	}

	return nil
}

func (m *OBAccount6) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if err := m.Status.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Status")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateStatusUpdateDateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.StatusUpdateDateTime) { // not required
		return nil
	}

	if err := m.StatusUpdateDateTime.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("StatusUpdateDateTime")
		}
		return err
	}

	return nil
}

func (m *OBAccount6) validateSwitchStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.SwitchStatus) { // not required
		return nil
	}

	if err := m.SwitchStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("SwitchStatus")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OBAccount6) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OBAccount6) UnmarshalBinary(b []byte) error {
	var res OBAccount6
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// OBAccount6AccountItems0 Provides the details to identify an account.
//
// swagger:model OBAccount6AccountItems0
type OBAccount6AccountItems0 struct {

	// identification
	// Required: true
	Identification Identification0 `json:"Identification"`

	// name
	Name Name0 `json:"Name,omitempty"`

	// scheme name
	// Required: true
	SchemeName OBExternalAccountIdentification4Code `json:"SchemeName"`

	// secondary identification
	SecondaryIdentification SecondaryIdentification `json:"SecondaryIdentification,omitempty"`
}

// Validate validates this o b account6 account items0
func (m *OBAccount6AccountItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIdentification(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchemeName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecondaryIdentification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OBAccount6AccountItems0) validateIdentification(formats strfmt.Registry) error {

	if err := m.Identification.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Identification")
		}
		return err
	}

	return nil
}

func (m *OBAccount6AccountItems0) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := m.Name.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Name")
		}
		return err
	}

	return nil
}

func (m *OBAccount6AccountItems0) validateSchemeName(formats strfmt.Registry) error {

	if err := m.SchemeName.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("SchemeName")
		}
		return err
	}

	return nil
}

func (m *OBAccount6AccountItems0) validateSecondaryIdentification(formats strfmt.Registry) error {

	if swag.IsZero(m.SecondaryIdentification) { // not required
		return nil
	}

	if err := m.SecondaryIdentification.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("SecondaryIdentification")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OBAccount6AccountItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OBAccount6AccountItems0) UnmarshalBinary(b []byte) error {
	var res OBAccount6AccountItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
