// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// OBExternalStatementInterestType1Code Interest amount type, in a coded form.
//
// swagger:model OBExternalStatementInterestType1Code
type OBExternalStatementInterestType1Code string

// Validate validates this o b external statement interest type1 code
func (m OBExternalStatementInterestType1Code) Validate(formats strfmt.Registry) error {
	return nil
}
