// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// OBExternalStatementAmountType1Code Amount type, in a coded form.
//
// swagger:model OBExternalStatementAmountType1Code
type OBExternalStatementAmountType1Code string

// Validate validates this o b external statement amount type1 code
func (m OBExternalStatementAmountType1Code) Validate(formats strfmt.Registry) error {
	return nil
}
