// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OBCodeMnemonic The four letter Mnemonic used within an XML file to identify a code
//
// swagger:model OB_CodeMnemonic
type OBCodeMnemonic string

// Validate validates this o b code mnemonic
func (m OBCodeMnemonic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^\\w{0,4}$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
