// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// OBExternalLegalStructureType1Code Legal standing of the party.
//
// swagger:model OBExternalLegalStructureType1Code
type OBExternalLegalStructureType1Code string

// Validate validates this o b external legal structure type1 code
func (m OBExternalLegalStructureType1Code) Validate(formats strfmt.Registry) error {
	return nil
}
